package com.isteer.sql.queries;

public class SqlQueries {

	public final static String ADD_USER = "INSERT INTO USER (USERNAME,USERFULLNAME,USEREMAIL,USERPASSWORD) VALUES(?,?,?,?)";

	public final static String ADD_ADDRESS = "INSERT INTO ADDRESS (FK_ADDRESS_USERID,ADDRESS) VALUES(?,?)";

	public final static String ADD_ROLES = "INSERT INTO AUTHORITY (FK_AUTHORITY_USERID,ROLE) VALUES(?,?)";

	public final static String UPDATE_USER = "UPDATE USER SET USERNAME=?,USERFULLNAME=?,USEREMAIL=?,USERPASSWORD=? WHERE USERID=?";

	public final static String UPDATE_USER_BY_ADMIN = "UPDATE USER SET USERNAME=?,USERFULLNAME=?,USEREMAIL=?,USERPASSWORD=?,ISACCOUNTNONEXPIRED=?,ISACCOUNTNONLOCKED=?,ISCREDENTIALSNONEXPIRED=?,ISENABLED=? WHERE USERID=?";

	public final static String DELETE_USER = "DELETE FROM USER WHERE USERID=?";

	public final static String DELETE_ADDRESS = "DELETE FROM ADDRESS WHERE FK_ADDRESS_USERID=?";

	public final static String DELETE_ROLES = "DELETE FROM AUTHORITY WHERE FK_AUTHORITY_USERID=?";

	public final static String GET_USER_BY_ID = "SELECT USERID,USERNAME,USERFULLNAME,USEREMAIL,USERPASSWORD,ISACCOUNTNONEXPIRED,ISACCOUNTNONLOCKED,ISCREDENTIALSNONEXPIRED,ISENABLED FROM USER WHERE USERID=?";

	public final static String GET_ADDRESS_BY_ID = "SELECT ADDRESS FROM ADDRESS WHERE FK_ADDRESS_USERID=?";

	public final static String GET_ROLES_BY_ID = "SELECT ROLE FROM AUTHORITY WHERE FK_AUTHORITY_USERID=?";

	public final static String GET_ALL_USERS = "SELECT USERID,USERNAME,USERFULLNAME,USEREMAIL,USERPASSWORD,ISACCOUNTNONEXPIRED,ISACCOUNTNONLOCKED,ISCREDENTIALSNONEXPIRED,"
			+ "ISENABLED,ADDRESS,ROLE FROM USER,ADDRESS,AUTHORITY WHERE USERID=FK_ADDRESS_USERID AND USERID=FK_AUTHORITY_USERID";

	public final static String GET_USER_BY_USERNAME = "SELECT USERID,USERNAME,USERFULLNAME,USEREMAIL,USERPASSWORD,ISACCOUNTNONEXPIRED,ISACCOUNTNONLOCKED,ISCREDENTIALSNONEXPIRED,ISENABLED FROM USER WHERE USERNAME=?";

	public final static String INSERT_PRIVILEGES = "INSERT INTO PRIVILEGES(FK_PRIVILEGES_USERID,PRIVILEGE) VALUES(?,?)";

	public final static String INSERT_USER_PRIVILEGES = "INSERT INTO PRIVILEGES(FK_PRIVILEGES_USERID) VALUES(?)";

	public final static String DELETE_PRIVILEGES = "DELETE FROM PRIVILEGES WHERE FK_PRIVILEGES_USERID=?";

	public final static String GET_PRIVILEGES = "SELECT PRIVILEGE FROM PRIVILEGES WHERE FK_PRIVILEGES_USERID=?";

	public final static String GET_ADDRESS_BY_USERID = "SELECT ADDRESS FROM ADDRESS WHERE FK_ADDRESS_USERID=?";

	public final static String GET_ADDRESS_BY_USERID_AND_ADDRESSID = "SELECT ADDRESS FROM ADDRESS WHERE FK_ADDRESS_USERID=? AND ADDRESSID=?";

	public final static String ADDRESS_ID_FOUNDER = "SELECT ADDRESS FROM ADDRESS WHERE ADDRESSID=?";
	
	public final static String ADD_END_POINT="INSERT INTO ENDPOINTS(ENDPOINTNAME) VALUES(?)";
	
	public final static String ADD_AUTHORIZATION="INSERT INTO AUTHORIZATION(FK_AUTHORIZATION_ENDPOINTSID,PRIVILEGE) VALUES(?,?)";
	
	public final static String DELETE_AUTHORIZATION="DELETE FROM AUTHORIZATION WHERE FK_AUTHORIZATION_ENDPOINTSID=?";
	
	public final static String END_POINT_ID_FOUNDER="SELECT ENDPOINTNAME FROM ENDPOINTS WHERE ENDPOINTID=?";
	
	public final static String GET_ALL_END_POINT="SELECT ENDPOINTID,ENDPOINTNAME FROM ENDPOINTS";
	
	public final static String GET_ALL_AUTHORIZATION="SELECT PRIVILEGE FROM AUTHORIZATION WHERE FK_AUTHORIZATION_ENDPOINTSID=?";
	
	
	
			                                       
	
	
	
	
	
	
	
	
	
	

}
